# Homework for Week 3

The goal for this homework is to see the relevant journalistic uses for what we learned in class in week 2.

1. access specific data within a dataset,
2. break down larger datasets into smaller chunks (subset),
3. Ingest different types of spreadsheets into Pandas,
4. Gather general info about our dataframes

# List Slicing
## Natural disasters list

The Small Business Administration has a list of natural disasters that cause extensive economic damage. Run the next cell to pull the list into memory

In [1]:
disasters = [
        "Landslides",
        "Earthquake",
        "Wildfires",
        "Tornadoes",
        "Hurricane",
        "Wind Storm",
        "Winter Freeze",
        "Ice Storm",
        "Drought",
        "Tsunami",
        "Flash floods",
        "Mudslides",
        "Torrential rainfall",
        "Riverine floods",
        "Tidal Surge"
         ]

In [2]:
## call the disaster list here
disasters

['Landslides',
 'Earthquake',
 'Wildfires',
 'Tornadoes',
 'Hurricane',
 'Wind Storm',
 'Winter Freeze',
 'Ice Storm',
 'Drought',
 'Tsunami',
 'Flash floods',
 'Mudslides',
 'Torrential rainfall',
 'Riverine floods',
 'Tidal Surge']

In [4]:
## the first item in the list
disasters[0]

'Landslides'

In [5]:
## call the penultimate item (without manually counting the number of items)
disasters[-2]

'Riverine floods'

### Clarification:

For the next two questions, I am referring to numerical positions rather than zero-indexed positions. In other words, you will have to translate the numerical position into zero-indexed positions in your slicing.

In [13]:
## create a new list called disasters_subset that holds the 3rd to 6th items inclusive
len(disasters)
disasters_subset = disasters[2:6]
disasters_subset

['Wildfires', 'Tornadoes', 'Hurricane', 'Wind Storm']

In [16]:
## create a new list called disasters_subset2 that holds the 2nd through 8th items
disasters_subset2 = disasters[1:8]
disasters_subset2

['Earthquake',
 'Wildfires',
 'Tornadoes',
 'Hurricane',
 'Wind Storm',
 'Winter Freeze',
 'Ice Storm']

## Pandas - Importing data

Please download from Google Drive the following data and then upload it into this notebook:

- <a href="https://drive.google.com/file/d/1izg0nXFm8vBJAhz77LFdSMQGP4STvpEk/view?usp=sharing">EMS excerpt</a>,

- <a href="https://docs.google.com/spreadsheets/d/1sUEttreon8IKzCmsfRQ6cPA1lfeuNDu9/edit?usp=sharing&ouid=107646296031550187966&rtpof=true&sd=true">Customs, Border Patrol</a>

**Give yourself time to download it. Some of the files are large!**

In [17]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems20_1st_6months_excerpt.csv``` into a dataframe named ```ems2020_excerpt_df```

In [22]:
## import data and store in dataframe
pd.read_csv("raw_data/ems20_1st_6months_excerpt.csv")
ems2020_excerpt_df = pd.read_csv("raw_data/ems20_1st_6months_excerpt.csv")

In [24]:
## call the first 10 rows
ems2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [26]:
## call the last 5 rows
ems2020_excerpt_df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [27]:
## call a 20 random rows
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
7760,200813756,2020-03-21 17:24:49,UNKNOW,4,UNKNOW,4,03/21/2020 05:24:49 PM,Y,0,03/21/2020 05:24:49 PM,...,33.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk168.csv
5117,201811866,2020-06-29 13:03:19,ANAPFC,2,ANAPFC,2,06/29/2020 01:03:37 PM,Y,18,06/29/2020 01:04:31 PM,...,61.0,46.0,315.0,22.0,9.0,N,N,N,N,chunk172.csv
10505,201161177,2020-04-25 10:22:22,CDBRFC,2,CDBRFC,2,04/25/2020 10:22:41 AM,Y,19,04/25/2020 10:23:07 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk170.csv
10878,200153002,2020-01-15 15:39:17,ABDPN,5,ABDPN,5,01/15/2020 03:39:57 PM,Y,40,01/15/2020 03:40:08 PM,...,94.0,33.0,301.0,14.0,12.0,N,N,N,N,chunk165.csv
3324,201301109,2020-05-09 10:06:56,INBLED,3,INBLED,3,05/09/2020 10:07:04 AM,Y,8,05/09/2020 10:08:05 AM,...,61.0,48.0,315.0,21.0,11.0,N,N,N,N,chunk170.csv
216,201222966,2020-05-01 19:13:30,UNKNOW,4,UNKNOW,4,05/01/2020 07:14:05 PM,Y,35,05/01/2020 07:14:11 PM,...,63.0,46.0,318.0,22.0,8.0,N,N,N,N,chunk170.csv
103,200361427,2020-02-05 10:15:22,CVAC,2,CVAC,2,02/05/2020 10:16:48 AM,Y,86,02/05/2020 10:17:06 AM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk166.csv
8869,200161956,2020-01-16 12:13:30,UNC,2,UNC,2,01/16/2020 12:13:37 PM,Y,7,01/16/2020 12:14:05 PM,...,70.0,48.0,314.0,22.0,9.0,N,N,N,N,chunk165.csv
11318,201512990,2020-05-30 19:15:13,DRUG,4,DRUG,4,05/30/2020 07:15:53 PM,Y,40,05/30/2020 07:16:18 PM,...,78.0,39.0,306.0,15.0,7.0,N,N,N,N,chunk171.csv
4003,201162342,2020-04-25 16:00:46,SEIZR,3,SEIZR,3,04/25/2020 04:01:08 PM,Y,22,04/25/2020 04:03:01 PM,...,49.0,15.0,211.0,11.0,14.0,N,N,N,N,chunk170.csv
3089,201403364,2020-05-19 21:42:29,MVAINJ,4,MVAINJ,4,05/19/2020 09:43:04 PM,Y,35,05/19/2020 09:43:16 PM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk171.csv
7700,201432125,2020-05-22 15:11:51,SICK,6,SICK,6,05/22/2020 03:13:32 PM,Y,101,05/22/2020 03:13:45 PM,...,48.0,15.0,206.0,9.0,15.0,N,N,N,N,chunk171.csv
8625,201103774,2020-04-19 23:19:58,EDP,7,EDP,7,04/19/2020 11:20:39 PM,Y,41,04/19/2020 11:21:00 PM,...,47.0,11.0,212.0,11.0,16.0,N,N,N,N,chunk170.csv
12214,200151401,2020-01-15 10:01:07,EDP,7,EDP,7,NaN,N,0,NaN,...,49.0,13.0,211.0,11.0,14.0,N,N,N,N,chunk165.csv
1626,200644106,2020-03-04 20:39:19,DRUG,4,DRUG,4,03/04/2020 08:40:24 PM,Y,65,03/04/2020 08:41:19 PM,...,46.0,15.0,205.0,9.0,15.0,N,N,N,N,chunk167.csv
8837,200964453,2020-04-05 17:34:10,TRAUMA,2,TRAUMA,2,04/05/2020 05:34:46 PM,Y,36,04/05/2020 05:34:52 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk169.csv
10496,200990201,2020-04-08 01:00:42,RESPIR,4,RESPIR,4,04/08/2020 01:00:52 AM,Y,10,04/08/2020 01:01:15 AM,...,66.0,44.0,312.0,20.0,10.0,N,N,N,N,chunk169.csv
11947,200050253,2020-01-05 01:18:37,ABDPN,5,ABDPN,5,01/05/2020 01:18:47 AM,Y,10,01/05/2020 01:20:15 AM,...,60.0,47.0,313.0,21.0,11.0,N,N,N,N,chunk165.csv
1216,200141361,2020-01-14 10:00:32,SICK,6,SICK,6,01/14/2020 10:07:40 AM,Y,428,01/14/2020 10:08:33 AM,...,48.0,15.0,206.0,9.0,15.0,N,N,N,N,chunk165.csv
10904,201042582,2020-04-13 13:29:45,SICK,6,SICK,6,04/13/2020 01:33:02 PM,Y,197,04/13/2020 01:33:02 PM,...,110.0,21.0,404.0,24.0,14.0,N,N,N,N,chunk169.csv

In [31]:
## how might you slice this df to show only rows 42 through 51 inclusive
ems2020_excerpt_df[42:52]

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
42,201542166,2020-06-02 14:39:16,CVAC,2,CVAC,2,06/02/2020 02:39:24 PM,Y,8,06/02/2020 02:39:43 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk171.csv
43,201290003,2020-05-08 00:02:09,EDP,7,EDP,7,05/08/2020 12:02:34 AM,Y,25,05/08/2020 12:02:55 AM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
44,201034249,2020-04-12 21:17:40,SICK,6,SICK,6,04/12/2020 09:20:33 PM,Y,173,04/12/2020 09:20:33 PM,...,75.0,37.0,305.0,19.0,8.0,N,N,N,N,chunk169.csv
45,201784219,2020-06-26 22:59:45,INJURY,5,INJURY,5,06/26/2020 10:59:54 PM,Y,9,06/26/2020 11:00:01 PM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk172.csv
46,201001249,2020-04-09 08:29:26,INJURY,5,INJURY,5,04/09/2020 08:29:30 AM,Y,4,04/09/2020 08:29:55 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk169.csv
47,200880324,2020-03-28 01:22:22,SICK,6,SICK,6,03/28/2020 01:23:56 AM,Y,94,03/28/2020 01:24:07 AM,...,5.0,1.0,101.0,2.0,7.0,N,N,N,N,chunk168.csv
48,201323660,2020-05-11 23:40:32,UNC,2,UNC,2,05/11/2020 11:40:43 PM,Y,11,05/11/2020 11:40:48 PM,...,40.0,8.0,201.0,7.0,15.0,Y,N,N,N,chunk170.csv
49,201632450,2020-06-11 16:18:15,TRAUMA,2,TRAUMA,2,06/11/2020 04:18:34 PM,Y,19,06/11/2020 04:19:07 PM,...,67.0,40.0,317.0,17.0,9.0,N,N,N,N,chunk171.csv
50,200630307,2020-03-03 02:35:05,SICK,6,SICK,6,03/03/2020 02:35:16 AM,Y,11,03/03/2020 02:35:46 AM,...,79.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
51,200314692,2020-01-31 22:35:56,STATEP,2,STATEP,2,01/31/2020 10:36:21 PM,Y,25,01/31/2020 10:36:32 PM,...,114.0,26.0,401.0,30.0,12.0,N,N,N,N,chunk166.csv

In [33]:
## store rows 42 through 51 inclusive into a df called df_excerpt
df_excerpt = ems2020_excerpt_df[42:52]
df_excerpt

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
42,201542166,2020-06-02 14:39:16,CVAC,2,CVAC,2,06/02/2020 02:39:24 PM,Y,8,06/02/2020 02:39:43 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk171.csv
43,201290003,2020-05-08 00:02:09,EDP,7,EDP,7,05/08/2020 12:02:34 AM,Y,25,05/08/2020 12:02:55 AM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
44,201034249,2020-04-12 21:17:40,SICK,6,SICK,6,04/12/2020 09:20:33 PM,Y,173,04/12/2020 09:20:33 PM,...,75.0,37.0,305.0,19.0,8.0,N,N,N,N,chunk169.csv
45,201784219,2020-06-26 22:59:45,INJURY,5,INJURY,5,06/26/2020 10:59:54 PM,Y,9,06/26/2020 11:00:01 PM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk172.csv
46,201001249,2020-04-09 08:29:26,INJURY,5,INJURY,5,04/09/2020 08:29:30 AM,Y,4,04/09/2020 08:29:55 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk169.csv
47,200880324,2020-03-28 01:22:22,SICK,6,SICK,6,03/28/2020 01:23:56 AM,Y,94,03/28/2020 01:24:07 AM,...,5.0,1.0,101.0,2.0,7.0,N,N,N,N,chunk168.csv
48,201323660,2020-05-11 23:40:32,UNC,2,UNC,2,05/11/2020 11:40:43 PM,Y,11,05/11/2020 11:40:48 PM,...,40.0,8.0,201.0,7.0,15.0,Y,N,N,N,chunk170.csv
49,201632450,2020-06-11 16:18:15,TRAUMA,2,TRAUMA,2,06/11/2020 04:18:34 PM,Y,19,06/11/2020 04:19:07 PM,...,67.0,40.0,317.0,17.0,9.0,N,N,N,N,chunk171.csv
50,200630307,2020-03-03 02:35:05,SICK,6,SICK,6,03/03/2020 02:35:16 AM,Y,11,03/03/2020 02:35:46 AM,...,79.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
51,200314692,2020-01-31 22:35:56,STATEP,2,STATEP,2,01/31/2020 10:36:21 PM,Y,25,01/31/2020 10:36:32 PM,...,114.0,26.0,401.0,30.0,12.0,N,N,N,N,chunk166.csv

In [36]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

type(df_excerpt)
df_excerpt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 42 to 51
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 10 non-null     int64
 1   INCIDENT_DATETIME               10 non-null     object
 2   INITIAL_CALL_TYPE               10 non-null     object
 3   INITIAL_SEVERITY_LEVEL_CODE     10 non-null     int64
 4   FINAL_CALL_TYPE                 10 non-null     object
 5   FINAL_SEVERITY_LEVEL_CODE       10 non-null     int64
 6   FIRST_ASSIGNMENT_DATETIME       10 non-null     object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  10 non-null     object
 8   DISPATCH_RESPONSE_SECONDS_QY    10 non-null     int64
 9   FIRST_ACTIVATION_DATETIME       10 non-null     object
 10  FIRST_ON_SCENE_DATETIME         10 non-null     object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  10 non-null     object
 12  INCIDENT_RESPONSE_SECONDS_QY    10 non-null     float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   10 non-null     float64
 14  FIRST_TO_HOSP_DATETIME          4 non-null      object
 15  FIRST_HOSP_ARRIVAL_DATETIME     4 non-null      object
 16  INCIDENT_CLOSE_DATETIME         10 non-null     object
 17  HELD_INDICATOR                  10 non-null     object
 18  INCIDENT_DISPOSITION_CODE       10 non-null     float64
 19  BOROUGH                         10 non-null     object
 20  INCIDENT_DISPATCH_AREA          10 non-null     object
 21  ZIPCODE                         10 non-null     float64
 22  POLICEPRECINCT                  10 non-null     float64
 23  CITYCOUNCILDISTRICT             10 non-null     float64
 24  COMMUNITYDISTRICT               10 non-null     float64
 25  COMMUNITYSCHOOLDISTRICT         10 non-null     float64
 26  CONGRESSIONALDISTRICT           10 non-null     float64
 27  REOPEN_INDICATOR                10 non-null     object
 28  SPECIAL_EVENT_INDICATOR         10 non-null     object
 29  STANDBY_INDICATOR               10 non-null     object
 30  TRANSFER_INDICATOR              10 non-null     object
 31  source                          10 non-null     object
dtypes: float64(9), int64(4), object(19)
memory usage: 2.6+ KB

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

In [49]:
## import data here
pd.read_excel("raw_data/multi-data.xlsx")
CBP_data = pd.read_excel("raw_data/multi-data.xlsx", sheet_name = "CBP", skiprows = 6)
CBP_data

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
...,...,...,...,...,...,...,...,...,...
95716,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95717,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [50]:
## call the top 15 rows
CBP_data.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [51]:
CBP_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB